name: Workflow

env:
  TWINE_USERNAME: "__token__"
  TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}

on:
  push:
    tags:
      - v*

permissions:
  contents: read

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - name: Version
        id: version
        run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
      - name: Is pre-release
        id: is_pre
        run: echo ::set-output name=IS_PRE::"$([[ ${{steps.version.outputs.version}} =~ .+-.+ ]] && echo 0 || echo 1)"
    outputs:
      version: ${{ steps.version.outputs.version }}
      is_pre: ${{ steps.is_pre.outputs.IS_PRE }}

  build:
    runs-on: ubuntu-latest
    needs: [version]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .[build]
      - name: Update version
        run: ./scripts/gen_version.py ${{ needs.version.outputs.version }}
      - name: Build
        run: python -m build
      - uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
